### ISSUE TITLE
 도메인은 com.misolab 으로 부탁합니다.

### ISSUE THREAD

**Issue by do-ockhyun** [do-ockhyun/greatedays-app#2]
플러터도 패키지명이 있었던거 같은데..
도메인은 `com.misolab` 으로 부탁합니다.

- com.misolab.greatedays.app
  - com.misolab.greatedays.app.ios
  - com.misolab.greatedays.app.android
 - com.misolab.greatedays.server (요건 서버)

**Comment by letitgobaby** [comment]
com.misolab.greatedays 으로 생성 했습니다

**Comment by do-ockhyun** [comment]
@letitgobaby 망했다. 그레이트가 'Great' 였네
